const products = [

// ============================================================
// ALIMENTAIRE (id 1 → 109)
// ============================================================
    { id: 1, name: "Huile de Tournesol", category: "alimentaire", image: "images/huile.webp", description: "Huile pure pression à froid", options: [{ type: "Litre", price: 1500, unit: "1L" }, { type: "Carton", price: 17000, unit: "12L" }], isMarketplace: false },
    { id: 2, name: "Huile Tournesol Lesieur 1L", category: "alimentaire", image: "images/huile-lesieur.webp", description: "Huile de tournesol raffinée", options: [{ type: "Bouteille", price: 1800, unit: "1L" }, { type: "Carton", price: 17000, unit: "12L" }], isMarketplace: false },
    { id: 3, name: "Huile Tournesol Lesueur 5L", category: "alimentaire", image: "images/huile-lesueur-5l.jpeg", description: "Huile de tournesol 5L", options: [{ type: "Bouteille", price: 8500, unit: "5L" }], isMarketplace: false },
    { id: 4, name: "Huile Tournesol Bonita 5L", category: "alimentaire", image: "images/huile-bonita-5L.webp", description: "Huile de tournesol 5L", options: [{ type: "Bidon", price: 8000, unit: "5L" }], isMarketplace: false },
    { id: 5, name: "Huile Tournesol Bonita 1L", category: "alimentaire", image: "images/huile-bonita-1l.jpeg", description: "Huile de tournesol 1L", options: [{ type: "Bouteille", price: 1700, unit: "1L" }, { type: "Carton", price: 18000, unit: "12L" }], isMarketplace: false },
    { id: 6, name: "Huile Tournesol Saint Maurice 5L", category: "alimentaire", image: "images/huile-Maurice-5l.webp", description: "Huile de tournesol 5L", options: [{ type: "Bidon", price: 8200, unit: "5L" }], isMarketplace: false },
    { id: 7, name: "Huile Tournesol Aïcha 1L", category: "alimentaire", image: "images/huile-aicha-1l.webp", description: "Huile de tournesol 1L", options: [{ type: "Bouteille", price: 1700, unit: "1L" }, { type: "Carton", price: 17300, unit: "12L" }], isMarketplace: false },
    { id: 8, name: "Huile Tournesol Aïcha 5L", category: "alimentaire", image: "images/huile-aicha-5l.webp", description: "Huile de tournesol 5L", options: [{ type: "Bidon", price: 8000, unit: "5L" }], isMarketplace: false },
    { id: 9, name: "Huile Tournesol Ok 1L", category: "alimentaire", image: "images/huile-ok-1l.webp", description: "Huile de tournesol 1L", options: [{ type: "Bouteille", price: 1650, unit: "1L" }, { type: "Carton", price: 16900, unit: "12L" }], isMarketplace: false },
    { id: 10, name: "Huile Tournesol Ok 5L", category: "alimentaire", image: "images/huile-ok-5l.webp", description: "Huile de tournesol 5L", options: [{ type: "Bidon", price: 7800, unit: "5L" }], isMarketplace: false },
    { id: 11, name: "Huile Tournesol Gino 1L", category: "alimentaire", image: "images/huile-gino-1l.webp", description: "Huile de tournesol 1L", options: [{ type: "Bouteille", price: 1700, unit: "1L" }, { type: "Carton", price: 17000, unit: "12L" }], isMarketplace: false },
    { id: 12, name: "Huile Tournesol Gino 5L", category: "alimentaire", image: "images/huile-gino-5l.webp", description: "Huile de tournesol 5L", options: [{ type: "Bidon", price: 8000, unit: "5L" }], isMarketplace: false },
    { id: 13, name: "Huile Tournesol 25L", category: "alimentaire", image: "images/huile-25l.webp", description: "Huile de tournesol 25L", options: [{ type: "Bidon", price: 38000, unit: "25L" }], isMarketplace: false },
    { id: 14, name: "Huile végétale", category: "alimentaire", image: "images/huile-vegetale.webp", description: "Huile végétale", options: [{ type: "Bouteille", price: 1500, unit: "1L" }], isMarketplace: false },
    { id: 15, name: "Huile rouge", category: "alimentaire", image: "images/huile-rouge.webp", description: "Huile de palme", options: [{ type: "Bouteille", price: 1200, unit: "1L" }, { type: "Bidon", price: 5500, unit: "5L" }], isMarketplace: false },

    { id: 16, name: "Riz Gino", category: "alimentaire", image: "images/Gino-5kg.webp", description: "Riz blanc de qualité", options: [{ type: "Sachet", price: 650, unit: "0.5kg" }, { type: "Sachet", price: 950, unit: "1kg" }, { type: "Sac", price: 7200, unit: "5kg" }], isMarketplace: false },
    { id: 17, name: "Riz Sister Grace", category: "alimentaire", image: "images/riz-sister-grace.webp", description: "Riz parfumé de qualité supérieure", options: [{ type: "Sachet", price: 600, unit: "0.5kg" }, { type: "Sachet", price: 850, unit: "1kg" }, { type: "Sac", price: 6500, unit: "5kg" }], isMarketplace: false },
    { id: 18, name: "Riz Délice", category: "alimentaire", image: "images/riz-delice.jpeg", description: "Riz blanc premium", options: [{ type: "Sac", price: 6500, unit: "5kg" }, { type: "Sac", price: 29000, unit: "25kg" }], isMarketplace: false },
    { id: 19, name: "Riz Rizière", category: "alimentaire", image: "images/riz-riziere.webp", description: "Riz local de bonne qualité", options: [{ type: "Sac", price: 4500, unit: "5kg" }, { type: "Sac", price: 20000, unit: "25kg" }], isMarketplace: false },
    { id: 20, name: "Riz Thaïlandais", category: "alimentaire", image: "images/riz-thai.webp", description: "Riz parfumé importé", options: [{ type: "Sac", price: 18000, unit: "25kg" }], isMarketplace: false },
    { id: 21, name: "Riz Ibo", category: "alimentaire", image: "images/riz-ibo.webp", description: "Riz blanc populaire", options: [{ type: "Bol", price: 1300, unit: "1bol" }, { type: "Kg", price: 1200, unit: "1kg" }], isMarketplace: false },
    { id: 22, name: "Riz Simple Standard", category: "alimentaire", image: "images/riz-standard.webp", description: "Riz économique pour usage quotidien", options: [{ type: "Bol", price: 1800, unit: "1bol" }, { type: "Kg", price: 1700, unit: "1kg" }], isMarketplace: false },
    { id: 23, name: "Riz Simple Meilleur", category: "alimentaire", image: "images/riz-meilleur.webp", description: "Riz amélioré, meilleure qualité", options: [{ type: "Bol", price: 1950, unit: "1bol" }, { type: "Kg", price: 1800, unit: "1kg" }], isMarketplace: false },

    { id: 24, name: "Couscous Dari", category: "alimentaire", image: "images/couscous-dari.webp", description: "Semoule de blé fine", options: [{ type: "Paquet", price: 500, unit: "500g" }, { type: "Carton", price: 11000, unit: "24x500g" }], isMarketplace: false },
    { id: 25, name: "Couscous Samia", category: "alimentaire", image: "images/couscous-samia.webp", description: "Semoule fine de qualité", options: [{ type: "Paquet", price: 650, unit: "500g" }, { type: "Carton", price: 14000, unit: "24x500g" }], isMarketplace: false },
    { id: 26, name: "Couscous Kayna", category: "alimentaire", image: "images/couscous-kayna.webp", description: "Semoule de blé", options: [{ type: "Paquet", price: 600, unit: "500g" }, { type: "Carton", price: 13000, unit: "24x500g" }], isMarketplace: false },
    { id: 27, name: "Couscous en vrac", category: "alimentaire", image: "images/couscous.webp", description: "Semoule vendue au kilogramme", options: [{ type: "Kg", price: 1350, unit: "1kg" }, { type: "Bol", price: 1400, unit: "Bol" }], isMarketplace: false },

    { id: 28, name: "Maïs", category: "alimentaire", image: "images/mais.webp", description: "Maïs sec pour consommation", options: [{ type: "Bol", price: 700, unit: "1bol" }, { type: "Sac", price: 18000, unit: "25kg" }], isMarketplace: false },
    { id: 29, name: "Gari", category: "alimentaire", image: "images/gari.webp", description: "Semoule de manioc", options: [{ type: "bol", price: 1300, unit: "bol" }, { type: "Sac", price: 12000, unit: "25kg" }], isMarketplace: false },
    { id: 30, name: "Farine de Maïs", category: "alimentaire", image: "images/farine-mais.webp", description: "Farine pour pâte et bouillie", options: [{ type: "Kg", price: 1000, unit: "1kg" }], isMarketplace: false },
    { id: 31, name: "Tapioca", category: "alimentaire", image: "images/tapioca.jpeg", description: "Granulés de manioc", options: [{ type: "Sachet", price: 50, unit: "1" }, { type: "Bol", price: 1800, unit: "bol" }], isMarketplace: false },
    { id: 32, name: "Sorgho", category: "alimentaire", image: "images/sorgho.webp", description: "Céréale locale", options: [{ type: "1 bol", price: 1000, unit: "1 bol" }], isMarketplace: false },
    { id: 33, name: "Haricot rouge", category: "alimentaire", image: "images/haricot-rouge.webp", description: "Haricot sec riche en protéines", options: [{ type: "1 bol", price: 2200, unit: "1 bol" }], isMarketplace: false },
    { id: 34, name: "Voandzou", category: "alimentaire", image: "images/voandzou.webp", description: "Légumineuse locale nutritive", options: [{ type: "1 bol", price: 3200, unit: "1 bol" }], isMarketplace: false },
    { id: 35, name: "Boule d'akassan", category: "alimentaire", image: "images/Boule-akassan.webp", description: "Préparation traditionnelle", options: [{ type: "Unité", price: 50, unit: "1" }], isMarketplace: false },
    { id: 36, name: "Atchèkè", category: "alimentaire", image: "images/atcheke.webp", description: "Semoule de manioc fermenté", options: [{ type: "Sachet", price: 200, unit: "1" }], isMarketplace: false },
    { id: 37, name: "Manioc séché et moulu", category: "alimentaire", image: "images/manioc-moulu.webp", description: "Farine de manioc", options: [{ type: "Kg", price: 1500, unit: "1kg" }], isMarketplace: false },
    { id: 38, name: "Manioc séché", category: "alimentaire", image: "images/manioc-seche.webp", description: "Manioc sec", options: [{ type: "bol", price: 1300, unit: "1" }], isMarketplace: false },
    { id: 39, name: "Arachide grillée", category: "alimentaire", image: "images/arachide-grillée.webp", description: "Arachides prêtes à consommer", options: [{ type: "la boite", price: 1000, unit: "1" }, { type: "Sacet", price: 25, unit: "1" }], isMarketplace: false },
    { id: 40, name: "Chips nature", category: "alimentaire", image: "images/chips.webp", description: "Chips croustillantes", options: [{ type: "Sachet", price: 200, unit: "100g" }], isMarketplace: false },
    { id: 41, name: "Argile blanche", category: "alimentaire", image: "images/argile.webp", description: "Argile comestible", options: [{ type: "Sachet", price: 25, unit: "1" }], isMarketplace: false },
    { id: 42, name: "Zakalê en boîte", category: "alimentaire", image: "images/Rupture.webp", description: "Produit local en conserve", options: [{ type: "Boîte", price: 100, unit: "1" }], isMarketplace: false },

    { id: 43, name: "Pain P4", category: "alimentaire", image: "images/pain-100.webp", description: "Pain format 100f", options: [{ type: "Unité", price: 100, unit: "1" }], isMarketplace: false },
    { id: 44, name: "Pain P3", category: "alimentaire", image: "images/pain-200.webp", description: "Pain format 200f", options: [{ type: "Unité", price: 200, unit: "1" }], isMarketplace: false },
    { id: 45, name: "Pain P2", category: "alimentaire", image: "images/pain-300.webp", description: "Pain format 300f", options: [{ type: "Unité", price: 300, unit: "1" }], isMarketplace: false },
    { id: 46, name: "Pain P1", category: "alimentaire", image: "images/pain-500.webp", description: "Pain format 500f", options: [{ type: "Unité", price: 500, unit: "1" }], isMarketplace: false },

    { id: 47, name: "Lait Peak poudre boîte gm", category: "alimentaire", image: "images/lait-peak-boite.webp", description: "Lait en poudre grande boîte", options: [{ type: "Boîte", price: 3200, unit: "gm" }], isMarketplace: false },
    { id: 48, name: "Lait Peak poudre Sachet gm", category: "alimentaire", image: "images/lait-peak-sachet.png", description: "Lait en poudre sachet", options: [{ type: "Sachet", price: 1700, unit: "gm" }, { type: "Carton", price: 50000, unit: "12" }], isMarketplace: false },
    { id: 49, name: "Lait Peak moyen", category: "alimentaire", image: "images/lait-peak-moyen.png", description: "Lait Peak format moyen", options: [{ type: "Boîte", price: 750, unit: "moyen" }], isMarketplace: false },
    { id: 50, name: "Lait Peak", category: "alimentaire", image: "images/lait-peak.webp", description: "Lait Peak", options: [{ type: "Boîte", price: 500, unit: "1" }], isMarketplace: false },
    { id: 51, name: "Lait Peak sachet pm", category: "alimentaire", image: "images/lait-peak-sachet-pm.png", description: "Lait Peak en sachet", options: [{ type: "Sachet", price: 150, unit: "1" }, { type: "Carton", price: 28000, unit: "12" }], isMarketplace: false },
    { id: 52, name: "Lait Bonnet Rouge 1", category: "alimentaire", image: "images/bonnet-rouge-1.webp", description: "Lait Bonnet Rouge format 1", options: [{ type: "Boîte", price: 1450, unit: "1" }, { type: "Carton", price: 28000, unit: "12" }], isMarketplace: false },
    { id: 53, name: "Lait Bonnet Rouge 2", category: "alimentaire", image: "images/bonnet-rouge-2.webp", description: "Lait Bonnet Rouge format 2", options: [{ type: "Boîte", price: 1450, unit: "2" }, { type: "Carton", price: 50000, unit: "12" }], isMarketplace: false },
    { id: 54, name: "Lait Cowbell gm", category: "alimentaire", image: "images/lait-cowbell-gm.webp", description: "Lait Cowbell grand modèle", options: [{ type: "Boîte", price: 750, unit: "gm" }], isMarketplace: false },
    { id: 55, name: "Lait Cowbell concentré", category: "alimentaire", image: "images/lait-cowbell-concentre.webp", description: "Lait concentré Cowbell", options: [{ type: "Boîte", price: 1200, unit: "1" }, { type: "Carton", price: 5500, unit: "12" }], isMarketplace: false },
    { id: 56, name: "Lait Cowbell sachet", category: "alimentaire", image: "images/lait-cowbell-sachet.webp", description: "Lait Cowbell en sachet", options: [{ type: "Sachet", price: 50, unit: "1" }, { type: "Carton", price: 2500, unit: "24" }], isMarketplace: false },
    { id: 57, name: "Lait Cèbon concentré", category: "alimentaire", image: "images/lait-cebon.webp", description: "Lait concentré Cèbon", options: [{ type: "Boîte", price: 1200, unit: "1" }, { type: "Carton", price: 13500, unit: "12" }], isMarketplace: false },
    { id: 58, name: "Lait Nido", category: "alimentaire", image: "images/lait-nido.png", description: "Lait Nido", options: [{ type: "Boîte", price: 2800, unit: "1" }], isMarketplace: false },
    { id: 59, name: "Lait Jago concentré", category: "alimentaire", image: "images/lait-jago.webp", description: "Lait concentré Jago", options: [{ type: "Boîte", price: 1200, unit: "1" }, { type: "Carton", price: 12700, unit: "12" }], isMarketplace: false },
    { id: 60, name: "Lait Miksi", category: "alimentaire", image: "images/lait-miksi.webp", description: "Lait Miksi", options: [{ type: "Boîte", price: 125, unit: "1" }], isMarketplace: false },

    { id: 61, name: "Nescafé Classic pm", category: "alimentaire", image: "images/nescafe-pm.png", description: "Nescafé petit modèle", options: [{ type: "Boîte", price: 700, unit: "pm" }], isMarketplace: false },
    { id: 62, name: "Nescafé Moyen", category: "alimentaire", image: "images/nescafe-moyen.webp", description: "Nescafé format moyen", options: [{ type: "Boîte", price: 2300, unit: "moyen" }], isMarketplace: false },
    { id: 63, name: "Nescafé sachet", category: "alimentaire", image: "images/nescafe-sachet.png", description: "Nescafé en sachet", options: [{ type: "Sachet", price: 50, unit: "1" }, { type: "Carton", price: 4800, unit: "1" }], isMarketplace: false },
    { id: 64, name: "Nescafé Tradicio pm", category: "alimentaire", image: "images/nescafe-tradicio.webp", description: "Nescafé Tradicio petit modèle", options: [{ type: "Boîte", price: 1950, unit: "pm" }], isMarketplace: false },
    { id: 65, name: "Milo Cowbell chocolat", category: "alimentaire", image: "images/milo-cowbell.webp", description: "Boisson chocolatée Milo Cowbell", options: [{ type: "Boîte", price: 150, unit: "1" }, { type: "Carton", price: 3200, unit: "24" }], isMarketplace: false },
    { id: 66, name: "Milo Cowbell chocolat gm", category: "alimentaire", image: "images/milo-cowbell-gm.jpg", description: "Milo Cowbell grand modèle", options: [{ type: "sachet", price: 950, unit: "gm" }], isMarketplace: false },
    { id: 67, name: "Milo Ovaltine", category: "alimentaire", image: "images/milo-ovaltine.webp", description: "Boisson chocolatée Ovaltine", options: [{ type: "Boîte", price: 2600, unit: "1" }], isMarketplace: false },
    { id: 68, name: "Milo Nestlé gm", category: "alimentaire", image: "images/milo-nestle.webp", description: "Milo Nestlé grand modèle", options: [{ type: "Boîte", price: 2600, unit: "gm" }], isMarketplace: false },
    { id: 69, name: "Milo sachet", category: "alimentaire", image: "images/milo-sachet.webp", description: "Milo en sachet", options: [{ type: "Sachet", price: 100, unit: "1" }, { type: "Carton", price: 2200, unit: "24" }], isMarketplace: false },
    { id: 70, name: "Miksi chocolat", category: "alimentaire", image: "images/miksi-chocolat.webp", description: "Boisson chocolatée Miksi", options: [{ type: "Boîte", price: 125, unit: "1" }], isMarketplace: false },

    { id: 71, name: "Bouillon Onga", category: "alimentaire", image: "images/bouillon-Onga.webp", description: "Cube d'assaisonnement", options: [{ type: "sachet de 15", price: 400, unit: "1" }, { type: "Carton", price: 3500, unit: "60" }], isMarketplace: false },
    { id: 72, name: "Bouillon Bonfood", category: "alimentaire", image: "images/bouillon-bonfood.webp", description: "Assaisonnement alimentaire", options: [{ type: "sachet de 15", price: 400, unit: "1" }, { type: "Carton", price: 3500, unit: "24" }], isMarketplace: false },
    { id: 73, name: "Bouillon Cookzen", category: "alimentaire", image: "images/bouillon-cokzen.webp", description: "Cube de bouillon", options: [{ type: "sachet de 15", price: 400, unit: "1" }, { type: "Carton", price: 3500, unit: "24" }], isMarketplace: false },
    { id: 74, name: "Bouillon Maggi", category: "alimentaire", image: "images/maggi.webp", description: "Cube d'assaisonnement populaire", options: [{ type: "sachet de 15", price: 450, unit: "1" }, { type: "Carton", price: 3700, unit: "24" }], isMarketplace: false },
    { id: 75, name: "Bouillon curry Onga", category: "alimentaire", image: "images/curry Onga.webp", description: "Assaisonnement au curry", options: [{ type: "Paquet", price: 350, unit: "1" }, { type: "Carton", price: 7500, unit: "24" }], isMarketplace: false },
    { id: 76, name: "Kivo (piment)", category: "alimentaire", image: "images/kivo.png", description: "kivo saveur piment", options: [{ type: "Sachet", price: 50, unit: "1" }], isMarketplace: false },
    { id: 77, name: "Curry Gino", category: "alimentaire", image: "images/curry-gino.webp", description: "Épice curry", options: [{ type: "Sachet", price: 100, unit: "1" }], isMarketplace: false },

    { id: 78, name: "Mayonnaise Bama", category: "alimentaire", image: "images/mayo-bama.png", description: "Mayonnaise Bama", options: [{ type: "Pot", price: 2300, unit: "1" }], isMarketplace: false },
    { id: 79, name: "Mayonnaise Sossa Sachet", category: "alimentaire", image: "images/mayo-sossa.webp", description: "Mayonnaise Sossa en sachet", options: [{ type: "Sachet", price: 50, unit: "1" }, { type: "Carton", price: 4500, unit: "24" }], isMarketplace: false },
    { id: 80, name: "Mayonnaise Aromate sachet", category: "alimentaire", image: "images/mayo-aromate.webp", description: "Mayonnaise aromatisée", options: [{ type: "Sachet", price: 50, unit: "1" }, { type: "Carton", price: 4500, unit: "24" }], isMarketplace: false },
    { id: 81, name: "Mayonnaise Jadida", category: "alimentaire", image: "images/mayo-jadida.webp", description: "Mayonnaise Jadida", options: [{ type: "Pot", price: 750, unit: "1" }], isMarketplace: false },
    { id: 82, name: "Mayonnaise Jm's", category: "alimentaire", image: "images/mayo-jms.webp", description: "Mayonnaise Jm's", options: [{ type: "Pot", price: 1350, unit: "1" }], isMarketplace: false },

    { id: 83, name: "Coquillettes pm", category: "alimentaire", image: "images/Coquillettes-pm.png", description: "Coquillettes petit modèle", options: [{ type: "Sachet", price: 200, unit: "pm" }, { type: "Carton", price: 5500, unit: "24" }], isMarketplace: false },
    { id: 84, name: "Coquillettes gm", category: "alimentaire", image: "images/Coquillettes-gm.webp", description: "Coquillettes grand modèle", options: [{ type: "Sachet", price: 400, unit: "gm" }, { type: "Carton", price: 11000, unit: "24" }], isMarketplace: false },
    { id: 85, name: "Vermicelle", category: "alimentaire", image: "images/vermicelle.webp", description: "Vermicelle", options: [{ type: "Sachet", price: 300, unit: "1" }, { type: "Carton", price: 6500, unit: "24" }], isMarketplace: false },
    { id: 86, name: "Indomie Grand", category: "alimentaire", image: "images/indomie-gm.webp", description: "Indomie grand format", options: [{ type: "Paquet", price: 400, unit: "gm" }, { type: "Carton", price: 7500, unit: "24" }], isMarketplace: false },
    { id: 87, name: "Indomie Petit", category: "alimentaire", image: "images/indomie-pm.webp", description: "Indomie petit format", options: [{ type: "Paquet", price: 250, unit: "pm" }, { type: "Carton", price: 4500, unit: "24" }], isMarketplace: false },
    { id: 88, name: "Spaghetti Bonita", category: "alimentaire", image: "images/spaghetti-bonita.png", description: "Spaghetti Bonita", options: [{ type: "Paquet", price: 400, unit: "1" }, { type: "Carton", price: 6800, unit: "10" }], isMarketplace: false },
    { id: 89, name: "Spaghetti p-2", category: "alimentaire", image: "images/spaghetti-p2.webp", description: "Spaghetti paquet 2", options: [{ type: "Paquet", price: 300, unit: "1" }, { type: "Carton", price: 5500, unit: "10" }], isMarketplace: false },
    { id: 90, name: "Spaghetti p-1", category: "alimentaire", image: "images/spaghetti-p1.png", description: "Spaghetti paquet 1", options: [{ type: "Paquet", price: 250, unit: "1" }, { type: "Carton", price: 4500, unit: "10" }], isMarketplace: false },
    { id: 91, name: "Spiral Rad gm", category: "alimentaire", image: "images/spiral-rad-gm.webp", description: "Pâtes spiralées grand modèle", options: [{ type: "Paquet", price: 400, unit: "gm" }, { type: "Carton", price: 11000, unit: "24" }], isMarketplace: false },
    { id: 92, name: "Beurre 250g", category: "alimentaire", image: "images/beurre-250g.webp", description: "Beurre 250g", options: [{ type: "Plaquette", price: 1500, unit: "250g" }], isMarketplace: false },

    { id: 93, name: "Sucre standard", category: "alimentaire", image: "images/sucre-standard.webp", description: "Sucre 1kg", options: [{ type: "Sac", price: 700, unit: "1kg" }, { type: "Sac", price: 15000, unit: "25kg" }], isMarketplace: false },
    { id: 94, name: "Sucre roux", category: "alimentaire", image: "images/sucre-roux.webp", description: "Sucre roux", options: [{ type: "Sac", price: 2200, unit: "1kg" }], isMarketplace: false },
    { id: 95, name: "Sucre St Louis gm", category: "alimentaire", image: "images/sucre-stlouis-gm.webp", description: "Sucre St Louis grand modèle", options: [{ type: "Sac", price: 1200, unit: "gm" }], isMarketplace: false },
    { id: 96, name: "Sucre St Louis pm", category: "alimentaire", image: "images/sucre-st-louis-pm.webp", description: "Sucre St Louis petit modèle", options: [{ type: "Sac", price: 700, unit: "pm" }], isMarketplace: false },
    { id: 97, name: "Vinaigre Rouge", category: "alimentaire", image: "images/vinaigre-rouge.webp", description: "Vinaigre rouge", options: [{ type: "Bouteille", price: 500, unit: "1" }], isMarketplace: false },
    { id: 98, name: "Vinaigre Blanc", category: "alimentaire", image: "images/vinaigre-blanc.webp", description: "Vinaigre blanc", options: [{ type: "Bouteille", price: 500, unit: "1" }], isMarketplace: false },
    { id: 99, name: "Petit pois Bonduelle", category: "alimentaire", image: "images/petit-pois.webp", description: "Petit pois Bonduelle", options: [{ type: "Boîte", price: 700, unit: "1" }, { type: "Carton", price: 13000, unit: "12" }], isMarketplace: false },
    { id: 100, name: "Tomate Aicha Moyen", category: "alimentaire", image: "images/tomate-aicha.webp", description: "Tomate Aicha format moyen", options: [{ type: "Boîte", price: 450, unit: "moyen" }, { type: "Carton", price: 5000, unit: "12" }], isMarketplace: false },
    { id: 101, name: "Tomate demi", category: "alimentaire", image: "images/tomate-demi.webp", description: "Tomate demi boîte", options: [{ type: "Boîte", price: 250, unit: "demi" }, { type: "Carton", price: 2800, unit: "12" }], isMarketplace: false },
    { id: 102, name: "Tomate sachet", category: "alimentaire", image: "images/tomate-sachet.webp", description: "Tomate concentré en sachet", options: [{ type: "sachet", price: 100, unit: "1" }, { type: "Carton", price: 4800, unit: "24" }], isMarketplace: false },
    { id: 103, name: "Sardine de variétés", category: "alimentaire", image: "images/sardine-variete.jpg", description: "Sardines variées", options: [{ type: "Boîte", price: 300, unit: "1" }, { type: "Carton", price: 8000, unit: "12" }], isMarketplace: false },
    { id: 104, name: "Sardines Apollo", category: "alimentaire", image: "images/sardine-apollo.webp", description: "Sardines Apollo", options: [{ type: "Boîte", price: 400, unit: "1" }, { type: "Carton", price: 8500, unit: "12" }], isMarketplace: false },
    { id: 105, name: "Sardines Safy", category: "alimentaire", image: "images/sardine-safy.webp", description: "Sardines Safy", options: [{ type: "Boîte", price: 500, unit: "1" }, { type: "Carton", price: 8500, unit: "12" }], isMarketplace: false },
    { id: 106, name: "Sardine Tinapa 555", category: "alimentaire", image: "images/sardine-555.webp", description: "Sardine Tinapa 555", options: [{ type: "Boîte", price: 550, unit: "1" }, { type: "Carton", price: 10000, unit: "12" }], isMarketplace: false },
    { id: 107, name: "Oeuf 1 Plateau", category: "alimentaire", image: "images/oeuf-plateau.webp", description: "Plateau d'œufs", options: [{ type: "Plateau", price: 2800, unit: "1" }, { type: "Unité", price: 100, unit: "1" }], isMarketplace: false },
    { id: 108, name: "Maïs en boite", category: "alimentaire", image: "images/maïs.png", description: "Maïs en boite", options: [{ type: "Boîte", price: 550, unit: "1" }, { type: "Carton", price: 6000, unit: "12" }], isMarketplace: false },

    // Espace réservé alimentaire (id 109 → 199)

// ============================================================
// BRICOLAGE (id 200 → 270)
// ============================================================
    { id: 200, name: "Rallonge de relais 2m", category: "bricolage", image: "images/rallonge-de-relais-2m.webp", description: "Rallonge professionnelle", options: [{ type: "Unité", price: 4500, unit: "1 pièce" }], isMarketplace: true },
    { id: 201, name: "Rallonge 4 trous", category: "bricolage", image: "images/ralonge-4.webp", description: "Rallonge électrique 4 prises", options: [{ type: "Unité", price: 3000, unit: "" }], isMarketplace: false },
    { id: 202, name: "Rallonge 5 trous 5m", category: "bricolage", image: "images/rallonge-5m.webp", description: "Rallonge 5 trous 5m de corde", options: [{ type: "Unité", price: 5500, unit: "" }], isMarketplace: false },
    { id: 203, name: "Multiprise sans fil P1", category: "bricolage", image: "images/multiprise_p1.jpg", description: "Multiprise sans fil", options: [{ type: "Unité", price: 700, unit: "" }], isMarketplace: false },
    { id: 204, name: "Multiprise sans fil P2", category: "bricolage", image: "images/multiprise-p2.webp", description: "Multiprise sans fil", options: [{ type: "Unité", price: 500, unit: "" }], isMarketplace: false },
    { id: 205, name: "Multiprise sans fil P3", category: "bricolage", image: "images/multiprise-p3.webp", description: "Multiprise sans fil", options: [{ type: "Unité", price: 600, unit: "" }], isMarketplace: false },
    { id: 206, name: "Multiprise sans fil P4", category: "bricolage", image: "images/multiprise_p4.jpg", description: "Multiprise sans fil", options: [{ type: "Unité", price: 500, unit: "" }], isMarketplace: false },
    { id: 207, name: "Multiprise sans fil P5", category: "bricolage", image: "images/multiprise_p5.jpg", description: "Multiprise sans fil", options: [{ type: "Unité", price: 1000, unit: "" }], isMarketplace: false },
    { id: 208, name: "Ampoule LED 50W", category: "bricolage", image: "images/ampoule-led-50w.webp", description: "Ampoule LED 50W", options: [{ type: "Unité", price: 1500, unit: "" }], isMarketplace: false },
    { id: 209, name: "Ampoule LED 60W", category: "bricolage", image: "images/ampoule-led-60w.webp", description: "Ampoule LED 60W", options: [{ type: "Unité", price: 2000, unit: "" }], isMarketplace: false },
    { id: 210, name: "Ampoule 10W-220", category: "bricolage", image: "images/ampoule-10w.webp", description: "Ampoule 10W", options: [{ type: "Unité", price: 800, unit: "" }], isMarketplace: false },
    { id: 211, name: "Ampoule jeu de lumière", category: "bricolage", image: "images/ampoule-jeu.webp", description: "Ampoule jeu de lumière", options: [{ type: "Unité", price: 2500, unit: "" }], isMarketplace: false },
    { id: 212, name: "Ventilo à pieds", category: "bricolage", image: "images/ventilo-pied.webp", description: "Ventilateur sur pieds", options: [{ type: "Unité", price: 15000, unit: "" }], isMarketplace: false },
    { id: 213, name: "Brasseur", category: "bricolage", image: "images/brasseur.jpg", description: "Brasseur de plafond", options: [{ type: "Unité", price: 13000, unit: "" }], isMarketplace: false },
    { id: 214, name: "Ventaille Simple", category: "bricolage", image: "images/ventaille-simple.webp", description: "Ventaille simple", options: [{ type: "Unité", price: 800, unit: "" }], isMarketplace: false },
    { id: 215, name: "Ventaille", category: "bricolage", image: "images/ventaille.webp", description: "Ventaille", options: [{ type: "Unité", price: 500, unit: "" }], isMarketplace: false },
    { id: 216, name: "Bougie Pm", category: "bricolage", image: "images/bougie-pm.webp", description: "Bougie petit modèle", options: [{ type: "Unité", price: 200, unit: "" }, { type: "Paquet", price: 2000, unit: "12" }], isMarketplace: false },
    { id: 217, name: "Bougie Gm", category: "bricolage", image: "images/bougie-gm.webp", description: "Bougie grand modèle", options: [{ type: "Unité", price: 500, unit: "" }, { type: "Paquet", price: 5000, unit: "12" }], isMarketplace: false },
    { id: 218, name: "Allumette Amen", category: "bricolage", image: "images/allumette-amen.webp", description: "Allumette Amen", options: [{ type: "Unité", price: 50, unit: "" }, { type: "Paquet", price: 500, unit: "12" }], isMarketplace: false },
    { id: 219, name: "Allumette Cuisy pot", category: "bricolage", image: "images/allumette-cuisy.webp", description: "Allumette Cuisy en pot", options: [{ type: "Unité", price: 200, unit: "" }], isMarketplace: false },
    { id: 220, name: "Colle Adhésive", category: "bricolage", image: "images/Adhesive.webp", description: "Colle adhésive", options: [{ type: "Unité", price: 500, unit: "" }], isMarketplace: false },
    { id: 221, name: "Colle Adhésive liquide", category: "bricolage", image: "images/colle-adhesive-liquide.webp", description: "Colle adhésive liquide", options: [{ type: "Unité", price: 750, unit: "" }], isMarketplace: false },
    { id: 222, name: "Chaise plastique", category: "bricolage", image: "images/chaise_plastique.jpg", description: "Chaise en plastique", options: [{ type: "Unité", price: 2500, unit: "" }], isMarketplace: false },
    { id: 223, name: "Chaise plastique", category: "bricolage", image: "images/plastique.jpg", description: "Plastique", options: [{ type: "Unité", price: 3500, unit: "" }], isMarketplace: false },
    { id: 224, name: "Balai à main", category: "bricolage", image: "images/balai-main.webp", description: "Balai à main", options: [{ type: "Unité", price: 500, unit: "" }], isMarketplace: false },
    { id: 225, name: "Balai à tige traditionnel", category: "bricolage", image: "images/balai-tige-traditionnel.webp", description: "Balai à tige traditionnel", options: [{ type: "Unité", price: 1000, unit: "" }], isMarketplace: false },
    { id: 226, name: "Balai moderne (tige)", category: "bricolage", image: "images/balai_moderne.jpg", description: "Balai moderne avec tige", options: [{ type: "Unité", price: 1500, unit: "" }], isMarketplace: false },
    { id: 227, name: "Balai à toile d'araignée", category: "bricolage", image: "images/balai_toile.jpg", description: "Balai toile d'araignée", options: [{ type: "Unité", price: 1200, unit: "" }], isMarketplace: false },
    { id: 228, name: "Brosse toilette", category: "bricolage", image: "images/brosse_toilette.jpg", description: "Brosse pour toilette", options: [{ type: "Unité", price: 1000, unit: "" }], isMarketplace: false },
    { id: 229, name: "Brosse à tige", category: "bricolage", image: "images/brosse-tige.webp", description: "Brosse à tige", options: [{ type: "Unité", price: 800, unit: "" }], isMarketplace: false },
    { id: 230, name: "Javel 5L", category: "bricolage", image: "images/javel-5l.webp", description: "Javel 5 litres", options: [{ type: "Unité", price: 2500, unit: "1" }], isMarketplace: false },
    { id: 231, name: "Javel gm", category: "bricolage", image: "images/javel-gm.webp", description: "Javel grand modèle", options: [{ type: "Unité", price: 1200, unit: "1" }], isMarketplace: false },
    { id: 232, name: "Javel liquide pm", category: "bricolage", image: "images/javel-pm.jpg", description: "Javel liquide petit modèle", options: [{ type: "Unité", price: 600, unit: "" }], isMarketplace: false },
    { id: 233, name: "Javel poudre", category: "bricolage", image: "images/javel-poudre.webp", description: "Javel en poudre", options: [{ type: "Unité", price: 50, unit: "1" }], isMarketplace: false },
    { id: 234, name: "Omo Yso", category: "bricolage", image: "images/omo_yso.png", description: "Omo Yso lessive", options: [{ type: "pm", price: 25, unit: "1" }, { type: "moyen", price: 100, unit: "1" }, { type: "gm", price: 275, unit: "1" }], isMarketplace: false },
    { id: 235, name: "Coton tige", category: "bricolage", image: "images/coton_tige.png", description: "Coton tige", options: [{ type: "Unité", price: 100, unit: "1" }], isMarketplace: false },
    { id: 236, name: "Lingette", category: "bricolage", image: "images/lingette.png", description: "Lingettes", options: [{ type: "Unité", price: 1000, unit: "1" }], isMarketplace: false },
    { id: 237, name: "Fourchette jetable", category: "bricolage", image: "images/fourchette_jetable.png", description: "Fourchettes jetables", options: [{ type: "Paquet", price: 1000, unit: "1" }], isMarketplace: false },
    { id: 238, name: "Cuillère jetable", category: "bricolage", image: "images/cuillere-jetable.webp", description: "Cuillères jetables", options: [{ type: "Paquet", price: 1500, unit: "1" }], isMarketplace: false },
    { id: 239, name: "Assiette jetable", category: "bricolage", image: "images/assiette_jetable.png", description: "Assiettes jetables", options: [{ type: "Paquet", price: 2000, unit: "1" }], isMarketplace: false },
    { id: 240, name: "Verre jetable", category: "bricolage", image: "images/verre_jetable.webp", description: "Verres jetables", options: [{ type: "Paquet", price: 1800, unit: "1" }], isMarketplace: false },
    { id: 241, name: "Taken away", category: "bricolage", image: "images/take_away.webp", description: "Boîte take away", options: [{ type: "1", price: 100, unit: "1" }, { type: "Paquet", price: 3500, unit: "1*36" }], isMarketplace: false },
    { id: 242, name: "Pipette", category: "bricolage", image: "images/pipette.png", description: "Pipettes / pailles", options: [{ type: "Paquet", price: 100, unit: "" }], isMarketplace: false },
    { id: 243, name: "Papier aluminium", category: "bricolage", image: "images/papier-aluminium.webp", description: "Papier aluminium", options: [{ type: "Unité", price: 800, unit: "" }], isMarketplace: false },
    { id: 244, name: "Papier Sopalain", category: "bricolage", image: "images/papier-sopalain.png", description: "Papier Sopala", options: [{ type: "Unité", price: 1800, unit: "1" }], isMarketplace: false },
    { id: 245, name: "Papier torchon", category: "bricolage", image: "images/papier-torchon.webp", description: "Papier torchon", options: [{ type: "Unité", price: 500, unit: "1" }], isMarketplace: false },
    { id: 246, name: "Papiers mouchoirs", category: "bricolage", image: "images/papiers_mouchoirs.png", description: "Mouchoirs en papier", options: [{ type: "Unité", price: 100, unit: "1" }, { type: "sachet", price: 900, unit: "sachet*10" }], isMarketplace: false },
    { id: 247, name: "Papier hygiénique Clean Soft", category: "bricolage", image: "images/papier_clean_soft.png", description: "Papier hygiénique Clean Soft", options: [{ type: "Unité", price: 150, unit: "" }, { type: "Paquet", price: 1700, unit: "12" }], isMarketplace: false },
    { id: 248, name: "Papier hygiénique Pride", category: "bricolage", image: "images/papier-pride.webp", description: "Papier hygiénique Pride", options: [{ type: "Unité", price: 200, unit: "1" }, { type: "Paquet", price: 2200, unit: "12" }], isMarketplace: false },
    { id: 249, name: "Papier hygiénique Garden", category: "bricolage", image: "images/papier-garden.webp", description: "Papier hygiénique Garden", options: [{ type: "Unité", price: 250, unit: "1" }, { type: "Paquet", price: 2800, unit: "12" }], isMarketplace: false },
    { id: 250, name: "Papier hygiénique Aqua Soft", category: "bricolage", image: "images/papier-aqua-soft.webp", description: "Papier hygiénique Aqua Soft", options: [{ type: "Unité", price: 100, unit: "1" }, { type: "Paquet", price: 900, unit: "12" }], isMarketplace: false },
    { id: 251, name: "Tampon Naval girl", category: "bricolage", image: "images/tampon_naval.webp", description: "Tampon Naval girl", options: [{ type: "Unité", price: 500, unit: "1" }], isMarketplace: false },
    { id: 252, name: "Tampon Maxplus", category: "bricolage", image: "images/tampon_maxplus.webp", description: "Tampon Maxplus", options: [{ type: "Unité", price: 650, unit: "1" }], isMarketplace: false },
    { id: 253, name: "Tampon Softcare", category: "bricolage", image: "images/tampon_softcare.webp", description: "Tampon Softcare", options: [{ type: "Unité", price: 600, unit: "1" }], isMarketplace: false },
    { id: 254, name: "Dentifrice Signal", category: "bricolage", image: "images/dentifrice-signal.webp", description: "Pâte dentifrice Signal", options: [{ type: "Unité", price: 800, unit: "1" }], isMarketplace: false },
    { id: 255, name: "Dentifrice Longrich", category: "bricolage", image: "images/dentifrice-longrich.webp", description: "Pâte dentifrice Longrich", options: [{ type: "Unité", price: 1200, unit: "1" }], isMarketplace: false },
    { id: 256, name: "Dentifrice Colgate", category: "bricolage", image: "images/dentifrice-colgate.webp", description: "Dentifrice Colgate", options: [{ type: "Unité", price: 900, unit: "1" }], isMarketplace: false },
    { id: 257, name: "Dentifrice Aquafresh", category: "bricolage", image: "images/dentifrice-aquafresh.webp", description: "Dentifrice Aquafresh", options: [{ type: "Unité", price: 900, unit: "1" }], isMarketplace: false },
    { id: 258, name: "Dentifrice Maxam gm", category: "bricolage", image: "images/dentifrice_maxam_gm.png", description: "Dentifrice Maxam grand modèle", options: [{ type: "Unité", price: 400, unit: "1" }], isMarketplace: false },
    { id: 259, name: "Dentifrice Maxam pm", category: "bricolage", image: "images/dentifrice_maxam_pm.png", description: "Dentifrice Maxam petit modèle", options: [{ type: "Unité", price: 200, unit: "1" }], isMarketplace: false },
    { id: 260, name: "Rasoir lord II", category: "bricolage", image: "images/Rasoir-Lord-II.webp", description: "rasoir barbe", options: [{ type: "Unité", price: 100, unit: "1" },{ type: "Paquet", price: 350, unit: "5" }], isMarketplace: false },
    { id: 261, name: "super-glue-Quality 1", category: "bricolage", image: "images/super-glue-Quality-1.webp", description: "Qualité 1", options: [{ type: "Unité", price: 150, unit: "1" }], isMarketplace: false },
    { id: 262, name: "super-glue-Quality 2", category: "bricolage", image: "images/super-glue-Quality-2.webp", description: "Qualité 2", options: [{ type: "Unité", price: 200, unit: "1" }], isMarketplace: false },
    { id: 263, name: "Omo genie", category: "bricolage", image: "images/omo_genie.jpg", description: "Omo genie lessive", options: [{ type: "pm", price: 25, unit: "1" }, { type: "moyen", price: 100, unit: "1" }, { type: "gm", price: 275, unit: "1" }], isMarketplace: false },
    { id: 264, name: "Omo Viva", category: "bricolage", image: "images/omo_viva.png", description: "Omo viva lessive", options: [{ type: "moyen", price: 100, unit: "1" }, { type: "gm", price: 900, unit: "1" }], isMarketplace: false },
    { id: 265, name: "Omo", category: "bricolage", image: "images/omo.png", description: "Omo lessive", options: [{ type: "gm", price: 1000, unit: "1" }], isMarketplace: false },
    { id: 266, name: "Omo Klin", category: "bricolage", image: "images/omo_Klin.png", description: "Omo Klin lessive", options: [{ type: "pm", price: 50, unit: "1" }], isMarketplace: false },
    { id: 267, name: "Pince habit", category: "bricolage", image: "images/pince.png", description: "Pince habit", options: [{ type: "pm", price: 600, unit: "1" }], isMarketplace: false },


    // Espace réservé bricolage (id 260 → 299)

    // ============================================================
// BOISSON (id 300 → 345)
// ============================================================
    { id: 300, name: "Eau Cristal 0.5L", category: "boisson", image: "images/eau_cristal_05.jpg", description: "Eau minérale", options: [{ type: "Bouteille", price: 200, unit: "0.5L" }, { type: "Carton", price: 4200, unit: "24" }], isMarketplace: false },
    { id: 301, name: "Eau Cristal 1.5L", category: "boisson", image: "images/eau-cristal-1-5.webp", description: "Eau minérale", options: [{ type: "Bouteille", price: 400, unit: "1.5L" }, { type: "Carton", price: 4500, unit: "12" }], isMarketplace: false },
    { id: 302, name: "Eau Perla 0.5L", category: "boisson", image: "images/eau-perla-05.webp", description: "Eau minérale", options: [{ type: "Bouteille", price: 200, unit: "0.5L" }, { type: "Carton", price: 4200, unit: "24" }], isMarketplace: false },
    { id: 303, name: "Eau Verna 0.5L", category: "boisson", image: "images/eau_verna-05.webp", description: "Eau minérale potable", options: [{ type: "Bouteille", price: 250, unit: "0.5L" }, { type: "Carton", price: 5500, unit: "24" }], isMarketplace: false },
    { id: 304, name: "Eau Voltic 0.5L", category: "boisson", image: "images/eau_voltic_05.webp", description: "Eau minérale potable", options: [{ type: "Bouteille", price: 200, unit: "0.5L" }, { type: "Carton", price: 4200, unit: "24" }], isMarketplace: false },
    { id: 305, name: "Eau Voltic 1.5L", category: "boisson", image: "images/eau_voltic_15.webp", description: "Eau minérale potable", options: [{ type: "Bouteille", price: 500, unit: "1.5L" }, { type: "Carton", price: 5500, unit: "12" }], isMarketplace: false },
    { id: 306, name: "Eau Voltic 5L", category: "boisson", image: "images/eau_voltic_5.webp", description: "Eau minérale potable", options: [{ type: "Bidon", price: 1500, unit: "5L" }], isMarketplace: false },
    { id: 307, name: "Eau Vitale 0.5L", category: "boisson", image: "images/eau-vitale-05.png", description: "Eau minérale potable", options: [{ type: "Bouteille", price: 200, unit: "0.5L" }, { type: "Carton", price: 2800, unit: "0.5L*24" }], isMarketplace: false },
    { id: 308, name: "Eau Vitale 1.5L", category: "boisson", image: "images/eau_vitale_15.webp", description: "Eau minérale potable", options: [{ type: "Bouteille", price: 450, unit: "1.5L" }, { type: "Carton", price: 4800, unit: "1.5L*12" }], isMarketplace: false },
    { id: 309, name: "Eau Vitale 5L", category: "boisson", image: "images/eau_vitale_5.webp", description: "Eau minérale potable", options: [{ type: "Bidon", price: 1400, unit: "5L" }, { type: "Carton", price: 6200, unit: "5L*4" }], isMarketplace: false },
    { id: 310, name: "Coca-Cola", category: "boisson", image: "images/coca.png", description: "Boisson gazeuse", options: [{ type: "Bouteille", price: 700, unit: "bouteille" }, { type: "Casier", price: 15000, unit: "24" }], isMarketplace: false },
    { id: 311, name: "Canette Coca-Cola", category: "boisson", image: "images/coca-canette.png", description: "Boisson gazeuse", options: [{ type: "Canette", price: 500, unit: "1" }, { type: "Paquet", price: 7500, unit: "24" }], isMarketplace: false },
    { id: 312, name: "Fanta 1.5L", category: "boisson", image: "images/fanta_1_5l.webp", description: "Boisson gazeuse", options: [{ type: "Bouteille", price: 900, unit: "1.5L" }, { type: "Sachet", price: 5200, unit: "1.5L*6" }], isMarketplace: false },
    { id: 313, name: "Canette Fanta", category: "boisson", image: "images/fanta_canette.webp", description: "Boisson gazeuse", options: [{ type: "Canette", price: 500, unit: "canette" }, { type: "Paquet", price: 7500, unit: "24" }], isMarketplace: false },
    { id: 314, name: "Sprite 1.5L", category: "boisson", image: "images/sprite_15.png", description: "Boisson gazeuse", options: [{ type: "Bouteille", price: 900, unit: "1.5L" }, { type: "Sachet", price: 3800, unit: "1.5L*6" }], isMarketplace: false },
    { id: 315, name: "Canette Sprite", category: "boisson", image: "images/sprite-canette.webp", description: "Boisson gazeuse", options: [{ type: "Canette", price: 400, unit: "canette" }, { type: "Paquet", price: 6000, unit: "24" }], isMarketplace: false },
    { id: 316, name: "Sega 1.5L", category: "boisson", image: "images/Sega-1.5L.webp", description: "Boisson gazeuse", options: [{ type: "Bouteille", price: 800, unit: "1.5L" }, { type: "Sachet", price: 4800, unit: "1.5L*6" }], isMarketplace: false },
    { id: 317, name: "Schweppes Tonic", category: "boisson", image: "images/schweppes_tonic.jpg ", description: "Boisson gazeuse tonic", options: [{ type: "Bouteille", price: 500, unit: "bouteille" }, { type: "Casier", price: 11000, unit: "24" }], isMarketplace: false },
    { id: 318, name: "Canette Mélange", category: "boisson", image: "images/canette_melange.webp", description: "Boisson mixte", options: [{ type: "Canette", price: 500, unit: "canette" }], isMarketplace: false },
    { id: 319, name: "Youki Cocktail 0.5L", category: "boisson", image: "images/youki_cocktail.jpg", description: "Boisson gazeuse fruitée", options: [{ type: "Bouteille", price: 300, unit: "0.5L" }, { type: "Carton", price: 6500, unit: "24" }], isMarketplace: false },
    { id: 320, name: "Youki Orange 1.5L", category: "boisson", image: "images/youki_orange_15.jpg", description: "Boisson gazeuse à l'orange", options: [{ type: "Bouteille", price: 900, unit: "1.5L" }, { type: "Carton", price: 5000, unit: "6" }], isMarketplace: false },
    { id: 321, name: "Malta Guinness", category: "boisson", image: "images/malta_guinness.jpg", description: "Boisson maltée non alcoolisée", options: [{ type: "Bouteille", price: 600, unit: "bouteille" }, { type: "Carton", price: 13000, unit: "24" }], isMarketplace: false },
    { id: 322, name: "3X Energy", category: "boisson", image: "images/3x_energy.png", description: "Boisson énergétique", options: [{ type: "Canette", price: 300, unit: "canette" }, { type: "Carton", price: 6500, unit: "24" }], isMarketplace: false },
    { id: 323, name: "Bigoo Coconut", category: "boisson", image: "images/bigoo_coconut.png", description: "Boisson énergétique", options: [{ type: "Bouteille", price: 300, unit: "bouteille" }, { type: "Paquet", price: 2600, unit: "24" }], isMarketplace: false },
    { id: 324, name: "Bigoo Tamarind", category: "boisson", image: "images/bigoo-tamarin.png", description: "Boisson énergétique", options: [{ type: "Bouteille", price: 300, unit: "bouteille" }, { type: "Paquet", price: 2600, unit: "24" }], isMarketplace: false },
    { id: 325, name: "Bigoo Apple", category: "boisson", image: "images/bigoo_apple.webp", description: "Boisson énergétique", options: [{ type: "Bouteille", price: 300, unit: "bouteille" }, { type: "Paquet", price: 2600, unit: "24" }], isMarketplace: false },
    { id: 326, name: "Bigoo Lemon", category: "boisson", image: "images/bigoo-lemon.webp", description: "Boisson énergétique", options: [{ type: "Bouteille", price: 300, unit: "bouteille" }, { type: "Paquet", price: 2600, unit: "24" }], isMarketplace: false },
    { id: 327, name: "Bigoo Rush", category: "boisson", image: "images/bigoo-rush.webp", description: "Boisson énergétique", options: [{ type: "Bouteille", price: 300, unit: "bouteille" }, { type: "Paquet", price: 2600, unit: "24" }], isMarketplace: false },
    { id: 328, name: "Bigoo Cocktail", category: "boisson", image: "images/bigoo_cocktail.webp", description: "Boisson énergétique", options: [{ type: "Bouteille", price: 300, unit: "bouteille" }, { type: "Paquet", price: 2600, unit: "24" }], isMarketplace: false },
    { id: 329, name: "Bigoo Cola", category: "boisson", image: "images/bigoo_cola.webp", description: "Boisson énergétique", options: [{ type: "Bouteille", price: 300, unit: "bouteille" }, { type: "Paquet", price: 2600, unit: "24" }], isMarketplace: false },
    { id: 330, name: "Heineken", category: "boisson", image: "images/heineken.webp", description: "Bière", options: [{ type: "Bouteille", price: 1000, unit: "bouteille" }, { type: "Paquet", price: 8200, unit: "bouteille*24" }], isMarketplace: false },
    { id: 331, name: "Canette bière Bkers", category: "boisson", image: "images/bkers.webp", description: "Bière en canette", options: [{ type: "Canette", price: 700, unit: "canette" }, { type: "Carton", price: 15000, unit: "24" }], isMarketplace: false },
    { id: 332, name: "Vin Blanc Vinapena", category: "boisson", image: "images/vin-blanc-vinapena.webp", description: "Vin blanc", options: [{ type: "Bouteille", price: 3000, unit: "bouteille" }], isMarketplace: false },
    { id: 333, name: "Vin Blanc Moulin de Launay", category: "boisson", image: "images/vin-blanc-moulin-de-LAUNAY.webp", description: "Vin blanc", options: [{ type: "Bouteille", price: 3200, unit: "bouteille" }], isMarketplace: false },
    { id: 334, name: "Vin rouge Merlo", category: "boisson", image: "images/vin-merlo.webp", description: "Vin rouge", options: [{ type: "Bouteille", price: 3000, unit: "bouteille" }], isMarketplace: false },
    { id: 335, name: "Vin rouge Gandia", category: "boisson", image: "images/vin-gandia.webp", description: "Vin rouge", options: [{ type: "Bouteille", price: 2800, unit: "bouteille" }], isMarketplace: false },
    { id: 336, name: "Vin rouge D Simon", category: "boisson", image: "images/vin-simon-carton-2.webp", description: "Vin rouge", options: [{ type: "Bouteille", price: 2500, unit: "bouteille" }], isMarketplace: false },
    { id: 337, name: "Vin rouge D Simon bouteille", category: "boisson", image: "images/vin-simon-bouteille.webp", description: "Vin rouge en bouteille", options: [{ type: "Bouteille", price: 2000, unit: "bouteille" }], isMarketplace: false },
    { id: 338, name: "Vin rouge D Simon carton", category: "boisson", image: "images/vin-simon-carton.webp", description: "Vin rouge en carton", options: [{ type: "Carton", price: 5000, unit: "carton" }], isMarketplace: false },
    { id: 339, name: "Champagne Moette", category: "boisson", image: "images/champagne-moette.png", description: "Champagne", options: [{ type: "Bouteille", price: 35000, unit: "bouteille" }], isMarketplace: false },
    { id: 340, name: "Champagne Charly", category: "boisson", image: "images/champagne_charly.png", description: "Champagne", options: [{ type: "Bouteille", price: 12000, unit: "bouteille" }], isMarketplace: false },
    { id: 341, name: "Café Rhum grande bouteille", category: "boisson", image: "images/cafe_rhum_grand.webp", description: "Boisson alcoolisée", options: [{ type: "Bouteille", price: 1500, unit: "bouteille" }], isMarketplace: false },
    { id: 342, name: "Café Rhum sachet", category: "boisson", image: "images/cafe-rhum.webp", description: "Boisson en sachet", options: [{ type: "Sachet", price: 100, unit: "sachet" }, { type: "Carton", price: 2200, unit: "24" }], isMarketplace: false },
    { id: 343, name: "Lipton 1 paquet", category: "boisson", image: "images/lipton.webp", description: "Thé Lipton", options: [{ type: "Paquet", price: 1200, unit: "paquet" }], isMarketplace: false },
    { id: 344, name: "Warba", category: "boisson", image: "images/warba.webp", description: "Boisson locale", options: [{ type: "Sachet", price: 150, unit: "sachet" }, { type: "Carton", price: 3500, unit: "24" }], isMarketplace: false },

    // Espace réservé boisson (id 345 → 399)


    // ============================================================
// ÉPICES & LÉGUMES (id 400 → 442)
// ============================================================
    { id: 400, name: "Tomate fraîche", category: "Epice", image: "images/tomate.webp", description: "Tomate fraîche", options: [{ type: "Sachet", price: 500, unit: "bol" }, { type: "Bol", price: 1000, unit: "bol" }], isMarketplace: false },
    { id: 401, name: "Oignon 25", category: "Epice", image: "images/oignon-25.webp", description: "Oignon de 25", options: [{ type: "Unité", price: 25, unit: "1" }, { type: "Lot", price: 1000, unit: "40" }], isMarketplace: false },
    { id: 402, name: "Oignon 50", category: "Epice", image: "images/oignon-50.webp", description: "Oignon de 50", options: [{ type: "Unité", price: 50, unit: "1" }, { type: "Lot", price: 1800, unit: "40" }], isMarketplace: false },
    { id: 403, name: "Oignon 100", category: "Epice", image: "images/oignon-100.webp", description: "Oignon de 100", options: [{ type: "Unité", price: 100, unit: "lot" }, { type: "Lot", price: 2600, unit: "40" }], isMarketplace: false },
    { id: 404, name: "Ail", category: "Epice", image: "images/ail.webp", description: "Ail", options: [{ type: "Sachet", price: 100, unit: "sachet" }, { type: "Lot", price: 500, unit: "lot" }], isMarketplace: false },
    { id: 405, name: "Piment vert", category: "Epice", image: "images/piment-vert.webp", description: "Piment vert", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 406, name: "Piment rouge", category: "Epice", image: "images/piment-rouge.webp", description: "Piment rouge", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 407, name: "Gingembre", category: "Epice", image: "images/Gingembre.webp", description: "Gingembre", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 408, name: "Clou de girofle", category: "Epice", image: "images/clou-girofle.webp", description: "Clou de girofle", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 409, name: "Baies de Selim", category: "Epice", image: "images/baies-selim.webp", description: "Baies de Selim", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 410, name: "Dekou", category: "Epice", image: "images/dekou.webp", description: "Dekou", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 411, name: "Mélange d'ingrédients", category: "Epice", image: "images/melange.webp", description: "Mélange d'ingrédients", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 412, name: "Basilic Africain Tchao", category: "Epice", image: "images/basilic.png", description: "Basilic africain", options: [{ type: "Botte", price: 500, unit: "botte" }], isMarketplace: false },
    { id: 413, name: "Feuille de Bissap", category: "Epice", image: "images/feuille-bissap.webp", description: "Feuille de bissap", options: [{ type: "Botte", price: 500, unit: "botte" }], isMarketplace: false },
    { id: 414, name: "Feuille de citronnelle", category: "Epice", image: "images/citronnelle.webp", description: "Feuille de citronnelle", options: [{ type: "Botte", price: 500, unit: "botte" }], isMarketplace: false },
    { id: 415, name: "Feuille d'ademe", category: "Epice", image: "images/ademe.webp", description: "Feuille d'ademe", options: [{ type: "Botte", price: 500, unit: "botte" }], isMarketplace: false },
    { id: 416, name: "Feuille de gboma", category: "Epice", image: "images/gboma.webp", description: "Feuille de gboma", options: [{ type: "Botte", price: 500, unit: "botte" }], isMarketplace: false },
    { id: 417, name: "Feuille de laurier", category: "Epice", image: "images/laurier.webp", description: "Feuille de laurier", options: [{ type: "Botte", price: 500, unit: "botte" }], isMarketplace: false },
    { id: 418, name: "Gombo frais", category: "Epice", image: "images/Gombo.webp", description: "Gombo frais", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 419, name: "Gombo sec", category: "Epice", image: "images/gombo-sec.webp", description: "Gombo sec", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 420, name: "Haricot vert", category: "Epice", image: "images/haricot-vert.webp", description: "Haricot vert", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 421, name: "Carotte", category: "Epice", image: "images/Carotte.webp", description: "Carotte", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 422, name: "Chou", category: "Epice", image: "images/chou.webp", description: "Chou", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 423, name: "Laitue", category: "Epice", image: "images/laitue.png", description: "Laitue", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 424, name: "Concombre", category: "Epice", image: "images/Concombre.webp", description: "Concombre", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 425, name: "Poivron", category: "Epice", image: "images/poivron.png", description: "Poivron", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 426, name: "Pomme de terre", category: "Epice", image: "images/pomme-de-terre.webp", description: "Pomme de terre", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 427, name: "Manioc", category: "Epice", image: "images/manioc.webp", description: "Manioc frais", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 428, name: "Patate douce", category: "Epice", image: "images/patate-douce.webp", description: "Patate douce", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 429, name: "Igname", category: "Epice", image: "images/igname.jpg", description: "Igname", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 430, name: "Betterave", category: "Epice", image: "images/Betterave.webp", description: "Betterave", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 431, name: "Ananas", category: "Epice", image: "images/Ananas.webp", description: "Ananas", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 432, name: "Mangue", category: "Epice", image: "images/Mangue.webp", description: "Mangue", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 433, name: "Papaye", category: "Epice", image: "images/Papaye.webp", description: "Papaye", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 434, name: "Banane", category: "Epice", image: "images/Banane.webp", description: "Banane", options: [{ type: "Main", price: 500, unit: "main" }], isMarketplace: false },
    { id: 435, name: "Pastèque", category: "Epice", image: "images/pasteque.webp", description: "Pastèque", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 436, name: "Avocat", category: "Epice", image: "images/Avocat.webp", description: "Avocat", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 437, name: "Raisins", category: "Epice", image: "images/Raisins.webp", description: "Raisins", options: [{ type: "Kg", price: 500, unit: "kg" }], isMarketplace: false },
    { id: 438, name: "Citron", category: "Epice", image: "images/Citron.webp", description: "Citron", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 439, name: "Pâte de maïs", category: "Epice", image: "images/pate_mais.jpg", description: "Pâte de maïs", options: [{ type: "Boule", price: 50, unit: "boule" }], isMarketplace: false },
    { id: 440, name: "Pâte de manioc", category: "Epice", image: "images/pate-manioc.webp", description: "Pâte de manioc", options: [{ type: "Boule", price: 50, unit: "boule" }], isMarketplace: false },
    { id: 441, name: "Pâte d'arachide", category: "Epice", image: "images/pate-arachide.webp", description: "Pâte d'arachide", options: [{ type: "Pot gm", price: 500, unit: "pot" }, { type: "Pot pm", price: 250, unit: "pot" }], isMarketplace: false },

    // Espace réservé épices (id 442 → 499)

// ============================================================
// FRAIS (id 500 → 520)
// ============================================================
    { id: 500, name: "Pilon de poulet", category: "frais", image: "images/pilon.webp", description: "Pilon de poulet", options: [{ type: "Kg", price: 1800, unit: "kg" }], isMarketplace: false },
    { id: 501, name: "Cuisse poulet moue", category: "frais", image: "images/cuisse-poulet-moue.webp", description: "Cuisse de poulet moue", options: [{ type: "Kg", price: 1800, unit: "kg" }], isMarketplace: false },
    { id: 502, name: "Cuisse poulet dure", category: "frais", image: "images/cuisse-poulet-dure.webp", description: "Cuisse de poulet dure", options: [{ type: "Kg", price: 1500, unit: "kg" }], isMarketplace: false },
    { id: 503, name: "Aile poulet moue", category: "frais", image: "images/Aile-poulet-moue.webp", description: "Aile de poulet moue", options: [{ type: "Kg", price: 1600, unit: "kg" }], isMarketplace: false },
    { id: 504, name: "Aile poulet dure", category: "frais", image: "images/Aile-poulet-dure.webp", description: "Aile de poulet dure", options: [{ type: "Kg", price: 1400, unit: "kg" }], isMarketplace: false },
    { id: 505, name: "Aile dindon petit", category: "frais", image: "images/Aile-dindon-petit.webp", description: "Aile de dindon petite", options: [{ type: "Kg", price: 1500, unit: "kg" }], isMarketplace: false },
    { id: 506, name: "Aile dindon grand", category: "frais", image: "images/Aile-dindon-grande.webp", description: "Aile de dindon grande", options: [{ type: "Kg", price: 1800, unit: "kg" }], isMarketplace: false },
    { id: 507, name: "Poulet surgelé", category: "frais", image: "images/poulet_surgelé.webp", description: "Poulet surgelé", options: [{ type: "Pièce", price: 4500, unit: "pièce" }], isMarketplace: false },
    { id: 508, name: "Saucisse douce", category: "frais", image: "images/saucisse_doux.webp", description: "Saucisse douce", options: [{ type: "Kg", price: 2500, unit: "kg" }], isMarketplace: false },
    { id: 509, name: "Saucisse simple", category: "frais", image: "images/saucisse_simple.webp", description: "Saucisse simple", options: [{ type: "Kg", price: 2000, unit: "kg" }], isMarketplace: false },
    { id: 510, name: "Poisson 17+", category: "frais", image: "images/poisson.webp", description: "Poisson taille 17+", options: [{ type: "Pièce", price: 800, unit: "pièce" }], isMarketplace: false },
    { id: 511, name: "Poisson 25+", category: "frais", image: "images/poisson-25+.webp", description: "Poisson taille 25+", options: [{ type: "Pièce", price: 1500, unit: "pièce" }], isMarketplace: false },
    { id: 512, name: "Poisson frit", category: "frais", image: "images/poisson-frit.webp", description: "Poisson frit", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 513, name: "Poisson fumé pm", category: "frais", image: "images/poisson-fume-pm2.webp", description: "Poisson fumé petit modèle", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 514, name: "Poisson fumé gm", category: "frais", image: "images/poisson-fume-gm2.webp", description: "Poisson fumé grand modèle", options: [{ type: "Pièce", price: 1500, unit: "pièce" }], isMarketplace: false },
    { id: 515, name: "Poisson séché", category: "frais", image: "images/poisson-seche.webp", description: "Poisson séché", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 516, name: "Poisson autre", category: "frais", image: "images/poisson.webp", description: "Autres types de poisson", options: [{ type: "Pièce", price: 500, unit: "pièce" }], isMarketplace: false },
    { id: 517, name: "Petit poisson Doèvi oukougan", category: "frais", image: "images/petit_poisson.webp", description: "Petit poisson Doèvi mémé oukougan", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 518, name: "Petit poisson Doèvi oukouvi", category: "frais", image: "images/petit_poisson.webp", description: "Petit poisson Doèvi mémé oukouvi", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },
    { id: 519, name: "Petit poisson séché Doèvisiasia", category: "frais", image: "images/petit_poisson_seche.webp", description: "Petit poisson séché Doèvisiasia", options: [{ type: "Sachet", price: 500, unit: "sachet" }], isMarketplace: false },

    // Espace réservé frais (id 520 → 599)

// ============================================================
// BÉBÉ (id 600 → 603)
// ============================================================
    { id: 600, name: "Trousseau bébé", category: "bebe", image: "images/trousseau_bebe.webp", description: "Trousseau complet pour bébé", options: [{ type: "Kit", price: 15000, unit: "kit" }], isMarketplace: false },
    { id: 601, name: "Couche bébé de 50", category: "bebe", image: "images/couche-bebe-50.webp", description: "Paquet de 50 couches bébé", options: [{ type: "Paquet", price: 8000, unit: "paquet" }], isMarketplace: false },
    { id: 602, name: "Couche Guetti F", category: "bebe", image: "images/couche-guetti-f.webp", description: "Couche Guetti taille F", options: [{ type: "Paquet", price: 5000, unit: "paquet" }], isMarketplace: false },
    { id: 603, name: "Berceau bébé", category: "bebe", image: "images/berceau_bebe.webp", description: "Berceau pour bébé", options: [{ type: "Pièce", price: 35000, unit: "pièce" }], isMarketplace: false },
    { id: 604, name: "Coton tige bébé", category: "bebe", image: "images/coton-tige_bebe.png", description: "Coton tige pour enfant pour bébé", options: [{ type: "Pièce", price: 200, unit: "pièce" }], isMarketplace: false },

    // Espace réservé bébé (id 604 → 699)

];
